/**
 * File writer for JS handler modules.
 * Writes .ts files to ui-react/src/generated/handlers/{databaseId}/{ModuleName}.ts
 */

const fs = require('fs');
const path = require('path');

const GENERATED_DIR = path.join(__dirname, '..', '..', '..', 'ui-react', 'src', 'generated', 'handlers');

/**
 * Escape a JS string for embedding in a template literal.
 * Backticks and ${...} sequences must be escaped.
 */
function escapeForTemplate(str) {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

/**
 * Escape a string for use as a JSON property value (double-quoted).
 */
function escapeJsonString(str) {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Write handler file to disk.
 *
 * @param {string} databaseId - Database slug (e.g. 'northwind4')
 * @param {string} moduleName - Module name (e.g. 'Form_frmAbout')
 * @param {Array} handlers - Array of handler objects from parseVbaToHandlers
 * @returns {{ filePath: string, relativePath: string }}
 */
function writeHandlerFile(databaseId, moduleName, handlers) {
  const dir = path.join(GENERATED_DIR, databaseId);
  fs.mkdirSync(dir, { recursive: true });

  const filename = `${moduleName}.ts`;
  const filePath = path.join(dir, filename);

  // Build handler entries
  const entries = handlers.map(h => {
    const key = h.key || `${h.control || 'form'}.${h.event || 'unknown'}`;
    return `  "${escapeJsonString(key)}": {
    key: "${escapeJsonString(key)}",
    control: "${escapeJsonString(h.control || '')}",
    event: "${escapeJsonString(h.event || '')}",
    procedure: "${escapeJsonString(h.procedure || '')}",
    js: "${escapeJsonString(h.js || '')}"
  }`;
  });

  const content = `// Auto-generated by AccessClone — do not edit manually
// Module: ${moduleName} | Database: ${databaseId}

export const handlers: Record<string, { key: string; control: string; event: string; procedure: string; js: string }> = {
${entries.join(',\n')}
};

export default handlers;
`;

  fs.writeFileSync(filePath, content, 'utf8');

  const relativePath = `ui-react/src/generated/handlers/${databaseId}/${filename}`;
  return { filePath, relativePath };
}

/**
 * Delete handler file from disk.
 */
function deleteHandlerFile(databaseId, moduleName) {
  const filePath = path.join(GENERATED_DIR, databaseId, `${moduleName}.ts`);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    return true;
  }
  return false;
}

/**
 * Check if a handler file exists on disk.
 */
function handlerFileExists(databaseId, moduleName) {
  const filePath = path.join(GENERATED_DIR, databaseId, `${moduleName}.ts`);
  return fs.existsSync(filePath);
}

/**
 * List all handler files for a database.
 */
function listHandlerFiles(databaseId) {
  const dir = path.join(GENERATED_DIR, databaseId);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.ts'))
    .map(f => f.replace('.ts', ''));
}

/**
 * Read handler file content from disk.
 * @returns {{ content: string }} or null if file doesn't exist
 */
function readHandlerFile(databaseId, moduleName) {
  const filePath = path.join(GENERATED_DIR, databaseId, `${moduleName}.ts`);
  if (!fs.existsSync(filePath)) return null;
  const content = fs.readFileSync(filePath, 'utf8');
  return { content };
}

/**
 * Write raw content to handler file verbatim (no auto-generation).
 */
function writeHandlerFileRaw(databaseId, moduleName, content) {
  const dir = path.join(GENERATED_DIR, databaseId);
  fs.mkdirSync(dir, { recursive: true });
  const filename = `${moduleName}.ts`;
  const filePath = path.join(dir, filename);
  fs.writeFileSync(filePath, content, 'utf8');
  const relativePath = `ui-react/src/generated/handlers/${databaseId}/${filename}`;
  return { filePath, relativePath };
}

module.exports = { writeHandlerFile, deleteHandlerFile, handlerFileExists, listHandlerFiles, readHandlerFile, writeHandlerFileRaw };
