-- Three Horse website pages — insert as unbound forms in the threehorse database
-- Run with: psql -U postgres -d polyaccess -f databases/threehorse/seed-pages.sql
--
-- NOTE: These forms are hand-authored (not imported from Access), so dimensions
-- are in PIXELS, not twips. The form renderer uses values directly as CSS pixels.

-- Clear any existing versions of these forms
DELETE FROM shared.forms WHERE database_id = 'threehorse' AND name IN ('About', 'Qualifying Analysis', 'How It Works');

-- ============================================================
-- About page
-- ============================================================
INSERT INTO shared.forms (database_id, name, definition, record_source, version, is_current, owner, modified_by)
VALUES ('threehorse', 'About', '{
  "id": "th-about",
  "name": "About",
  "caption": "About Three Horse",
  "width": 600,
  "popup": 0,
  "modal": 0,
  "allow-additions": 0,
  "allow-deletions": 0,
  "allow-edits": 0,
  "navigation-buttons": 0,
  "record-selectors": 0,
  "dividing-lines": 0,
  "data-entry": 0,
  "default-view": "Single Form",
  "header": {
    "height": 120,
    "back-color": "#FFFFFF",
    "controls": [
      {
        "type": "image",
        "name": "imgHeader",
        "picture": "/images/three-horses-header.png",
        "size-mode": "cover",
        "picture-alignment": "right",
        "x": 0,
        "y": 0,
        "width": 600,
        "height": 120,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblTitle",
        "caption": "Three Horse",
        "x": 14,
        "y": 80,
        "width": 570,
        "height": 30,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 22,
        "font-weight": 700,
        "fore-color": "#FFFFFF",
        "back-style": 0
      }
    ]
  },
  "detail": {
    "height": 580,
    "controls": [
      {
        "type": "label",
        "name": "lblTagline",
        "caption": "Legacy database applications, migrated to the web with an AI partner.",
        "x": 14,
        "y": 10,
        "width": 570,
        "height": 24,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 14,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblProblem",
        "caption": "The Problem",
        "x": 14,
        "y": 50,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblProblemText",
        "caption": "Millions of small business applications were built in Access, FoxPro, and Paradox. The original developers are gone. The platforms are dead or dying. The apps still work but can''t be extended, can''t run on the web, and break when Windows updates. The alternative is a manual rewrite at $30-50k+. Most businesses can''t afford it.",
        "x": 14,
        "y": 72,
        "width": 570,
        "height": 55,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblSolution",
        "caption": "What We Do",
        "x": 14,
        "y": 145,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblSolutionText",
        "caption": "Three Horse converts your legacy database application into a modern web app backed by PostgreSQL. Tables, queries, forms, reports, and business logic are all migrated. The result is a working application accessible from any browser, with multiple simultaneous users and no desktop dependency.",
        "x": 14,
        "y": 167,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblPartner",
        "caption": "The AI Partner",
        "x": 14,
        "y": 235,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblPartnerText",
        "caption": "Every migrated application includes a built-in AI assistant that understands the full context: schema, forms, reports, event handlers, and the dependency graph. Ask it to explain how things work, make changes, build new features, or troubleshoot issues. It generates validated intent trees rather than raw code — predictable, reversible, and understandable.",
        "x": 14,
        "y": 257,
        "width": 570,
        "height": 55,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblPlatforms",
        "caption": "Supported Platforms",
        "x": 14,
        "y": 330,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblPlatformsText",
        "caption": "Microsoft Access (.accdb, .mdb) — working today. Visual FoxPro — next target. Borland Paradox — planned. Spreadsheets (.xlsx) — planned. One runtime, multiple source adapters.",
        "x": 14,
        "y": 352,
        "width": 570,
        "height": 40,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      }
    ]
  },
  "footer": {
    "height": 30,
    "back-color": "#F8F9FA",
    "controls": [
      {
        "type": "label",
        "name": "lblFooter",
        "caption": "three.horse — Legacy migration with an AI partner",
        "x": 14,
        "y": 8,
        "width": 570,
        "height": 14,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 9,
        "fore-color": "#7F8C8D",
        "back-style": 0
      }
    ]
  }
}'::jsonb, NULL, 1, true, 'standard', 'system');

-- ============================================================
-- Qualifying Analysis page
-- ============================================================
INSERT INTO shared.forms (database_id, name, definition, record_source, version, is_current, owner, modified_by)
VALUES ('threehorse', 'Qualifying Analysis', '{
  "id": "th-qualifying",
  "name": "Qualifying Analysis",
  "caption": "Qualifying Analysis",
  "width": 600,
  "popup": 0,
  "modal": 0,
  "allow-additions": 0,
  "allow-deletions": 0,
  "allow-edits": 0,
  "navigation-buttons": 0,
  "record-selectors": 0,
  "dividing-lines": 0,
  "data-entry": 0,
  "default-view": "Single Form",
  "header": {
    "height": 120,
    "back-color": "#FFFFFF",
    "controls": [
      {
        "type": "image",
        "name": "imgHeader",
        "picture": "/images/three-horses-header.png",
        "size-mode": "cover",
        "picture-alignment": "right",
        "x": 0,
        "y": 0,
        "width": 600,
        "height": 120,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblTitle",
        "caption": "Qualifying Analysis",
        "x": 14,
        "y": 80,
        "width": 570,
        "height": 30,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 22,
        "font-weight": 700,
        "fore-color": "#FFFFFF",
        "back-style": 0
      }
    ]
  },
  "detail": {
    "height": 530,
    "controls": [
      {
        "type": "label",
        "name": "lblIntro",
        "caption": "See exactly what''s in your Access database before committing to anything.",
        "x": 14,
        "y": 10,
        "width": 570,
        "height": 24,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 14,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblWhatIs",
        "caption": "What It Does",
        "x": 14,
        "y": 46,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblWhatIsText",
        "caption": "The qualifying analysis tool scans your Access database and produces a detailed diagnostic report. It catalogs every table, query, form, report, VBA module, macro, and relationship. It identifies complexity, external dependencies, and potential migration issues. The report gives you — and us — a clear picture of what your application does and what migration would involve.",
        "x": 14,
        "y": 68,
        "width": 570,
        "height": 55,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblSafe",
        "caption": "Safe and Private",
        "x": 14,
        "y": 140,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblSafeText",
        "caption": "The tool is read-only — it does not modify your database. It runs locally on your machine. No data leaves your computer. The report is a text file you can review, share, or paste into any AI assistant for further analysis.",
        "x": 14,
        "y": 162,
        "width": 570,
        "height": 45,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblReport",
        "caption": "What the Report Shows",
        "x": 14,
        "y": 225,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblReportText",
        "caption": "Object counts and inventory. Table structures with field counts, row counts, and primary key status. Query categorization (select, action, crosstab). Form complexity (controls, events, subforms, combo boxes). VBA module analysis with external dependency flags. Relationship mapping. Findings organized by severity (error, warning, info). Migration readiness assessment across schema, queries, forms, and VBA dimensions.",
        "x": 14,
        "y": 247,
        "width": 570,
        "height": 65,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblHow",
        "caption": "How to Get Started",
        "x": 14,
        "y": 330,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblHowText",
        "caption": "1. Download the qualifying analysis tool (a PowerShell script — Windows only, since that''s where Access databases live). 2. Run it against your .accdb or .mdb file. 3. Review the report. 4. If you want to discuss it, paste the report into the chat on this page or bring it back to three.horse.",
        "x": 14,
        "y": 352,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblFree",
        "caption": "The qualifying analysis is free. No commitment, no signup required.",
        "x": 14,
        "y": 420,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 12,
        "font-weight": 700,
        "fore-color": "#27AE60",
        "back-style": 0
      }
    ]
  },
  "footer": {
    "height": 30,
    "back-color": "#F8F9FA",
    "controls": [
      {
        "type": "label",
        "name": "lblFooter",
        "caption": "three.horse — Legacy migration with an AI partner",
        "x": 14,
        "y": 8,
        "width": 570,
        "height": 14,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 9,
        "fore-color": "#7F8C8D",
        "back-style": 0
      }
    ]
  }
}'::jsonb, NULL, 1, true, 'standard', 'system');

-- ============================================================
-- How It Works page
-- ============================================================
INSERT INTO shared.forms (database_id, name, definition, record_source, version, is_current, owner, modified_by)
VALUES ('threehorse', 'How It Works', '{
  "id": "th-howitworks",
  "name": "How It Works",
  "caption": "How It Works",
  "width": 600,
  "popup": 0,
  "modal": 0,
  "allow-additions": 0,
  "allow-deletions": 0,
  "allow-edits": 0,
  "navigation-buttons": 0,
  "record-selectors": 0,
  "dividing-lines": 0,
  "data-entry": 0,
  "default-view": "Single Form",
  "header": {
    "height": 120,
    "back-color": "#FFFFFF",
    "controls": [
      {
        "type": "image",
        "name": "imgHeader",
        "picture": "/images/three-horses-header.png",
        "size-mode": "cover",
        "picture-alignment": "right",
        "x": 0,
        "y": 0,
        "width": 600,
        "height": 120,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblTitle",
        "caption": "How It Works",
        "x": 14,
        "y": 80,
        "width": 570,
        "height": 30,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 22,
        "font-weight": 700,
        "fore-color": "#FFFFFF",
        "back-style": 0
      }
    ]
  },
  "detail": {
    "height": 680,
    "controls": [
      {
        "type": "label",
        "name": "lblIntro",
        "caption": "From Access database to working web application — step by step.",
        "x": 14,
        "y": 10,
        "width": 570,
        "height": 24,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 14,
        "fore-color": "#2C3E50",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep1",
        "caption": "Step 1: Qualifying Analysis",
        "x": 14,
        "y": 46,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep1Text",
        "caption": "A diagnostic tool scans your Access database and produces a detailed report — object inventory, complexity assessment, dependency analysis, and migration readiness score. This shows exactly what your application does and what the migration covers. Free, read-only, runs locally.",
        "x": 14,
        "y": 68,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep2",
        "caption": "Step 2: Tables & Schema",
        "x": 14,
        "y": 130,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep2Text",
        "caption": "Every Access table becomes a PostgreSQL table with proper data types, constraints, and relationships. Each database gets its own schema (namespace) for clean isolation. Data is migrated row by row. Primary keys, foreign keys, and indexes are preserved.",
        "x": 14,
        "y": 152,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep3",
        "caption": "Step 3: Queries",
        "x": 14,
        "y": 214,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep3Text",
        "caption": "Access SQL is converted to PostgreSQL. Select queries become views. Action queries become functions. A regex converter handles ~90% automatically; an AI fallback handles the rest. A multi-pass retry loop resolves dependency ordering (query A depends on query B depends on query C).",
        "x": 14,
        "y": 236,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep4",
        "caption": "Step 4: Forms & Reports",
        "x": 14,
        "y": 298,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep4Text",
        "caption": "Access forms become JSON definitions rendered in the browser. Layout is preserved — controls appear at the same positions with the same sizes. Text boxes, buttons, combo boxes, subforms, tab controls, continuous forms, and record navigation all work. Reports use a banded layout with group breaks and page formatting.",
        "x": 14,
        "y": 320,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep5",
        "caption": "Step 5: Business Logic",
        "x": 14,
        "y": 382,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep5Text",
        "caption": "VBA code is not translated line-by-line. Instead, the intent is extracted — what the code is trying to accomplish. The result is structured intent trees: ''open that form filtered to this customer'', ''look up the price and fill it in'', ''validate required fields''. A client-side runtime executes these intent trees. 23 of 30 intent types are mechanical (no AI needed).",
        "x": 14,
        "y": 404,
        "width": 570,
        "height": 55,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep6",
        "caption": "Step 6: Delivery",
        "x": 14,
        "y": 471,
        "width": 570,
        "height": 20,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 13,
        "font-weight": 700,
        "fore-color": "#2980B9",
        "back-style": 0
      },
      {
        "type": "label",
        "name": "lblStep6Text",
        "caption": "A working web application accessible from any browser. Multiple simultaneous users. No desktop dependency. Version-controlled forms and reports. Built-in AI partner that understands the application and can help you modify it going forward. Fixed price — no hourly billing, no surprises.",
        "x": 14,
        "y": 493,
        "width": 570,
        "height": 50,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 11,
        "fore-color": "#444444",
        "back-style": 0
      }
    ]
  },
  "footer": {
    "height": 30,
    "back-color": "#F8F9FA",
    "controls": [
      {
        "type": "label",
        "name": "lblFooter",
        "caption": "three.horse — Legacy migration with an AI partner",
        "x": 14,
        "y": 8,
        "width": 570,
        "height": 14,
        "visible": 1,
        "enabled": 1,
        "locked": 0,
        "tab-stop": 0,
        "font-size": 9,
        "fore-color": "#7F8C8D",
        "back-style": 0
      }
    ]
  }
}'::jsonb, NULL, 1, true, 'standard', 'system');
